### http://localhost:4111/api/v1/auth/login
POST {   "username": "admin",   "password": "admin" }
Content-Type: application/json

>> http://localhost:4111/api/v1/auth/login/response-{{$timestamp}}.json

